### ISSUE TITLE
Guildstats tabs number changed

### ISSUE THREAD

**Issue by Tschis** [mathiasbynens/tibia.com-extension#16]
https://github.com/mathiasbynens/tibia.com-extension/blob/5afc155a323945a7895b474b6f7e67ce87e3e7f0/js/character.js#L114

Should be now `tab=9`

e.g.
https://guildstats.eu/character?nick=Veyllor&tab=7
https://guildstats.eu/character?nick=Veyllor&tab=9

**Comment by mathiasbynens** [comment]
This has been fixed and will be part of the v2.2.2 release. Thanks!
