### ISSUE TITLE
question

### ISSUE THREAD

**Issue by guilherme22** [mathiasbynens/tibia.com-extension#8]
are you old Mathias Bynes that played in xantera, time of Kal-torak? :)

**Comment by mathiasbynens** [comment]
Yep, that's me! Is that you, Ted'suss?

**Comment by guilherme22** [comment]
hahaha nice !
No no, i played later this war...I'm Elva Gren.
hahaha i already sent you an invite, i see that you have Illja in facebook 👍 
Hugs!

**Comment by mathiasbynens** [comment]
What's up Elva! <3

**Comment by alexandreo** [comment]
i am ted'suss =)

**Comment by mathiasbynens** [comment]
O hey Ted'suss! <3 Long time since you blocked giant spiders for me in PoH! What's up dude?
